// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251229151310_AddEmpleadoIdToUsuario")]
    partial class AddEmpleadoIdToUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Tecnología de la Información",
                            Nombre = "TI"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Mantenimiento de instalaciones",
                            Nombre = "Mantenimiento"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Gestión de transporte",
                            Nombre = "Transporte"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Adquisiciones y compras",
                            Nombre = "Compras"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("Domain.Entities.HistorialEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialEstados");
                });

            modelBuilder.Entity("Domain.Entities.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchivoContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchivoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchivoRuta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GestorAsignadoId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("int");

                    b.Property<int>("TipoSolicitudId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("GestorAsignadoId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("SolicitanteId");

                    b.HasIndex("TipoSolicitudId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("Domain.Entities.TipoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("TiposSolicitud");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            AreaId = 1,
                            Descripcion = "Soporte técnico de computadoras",
                            Nombre = "Soporte PC"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            AreaId = 1,
                            Descripcion = "Solicitud de acceso a sistemas",
                            Nombre = "Acceso a Sistema"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            AreaId = 2,
                            Descripcion = "Reparación de instalaciones",
                            Nombre = "Reparación"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            AreaId = 3,
                            Descripcion = "Solicitud de vehículo",
                            Nombre = "Asignación de Vehículo"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            AreaId = 4,
                            Descripcion = "Solicitud de compra",
                            Nombre = "Compra de Material"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmpleadoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "superadmin@solicitudes.com",
                            FechaCreacion = new DateTime(2025, 12, 29, 11, 13, 9, 458, DateTimeKind.Local).AddTicks(1662),
                            Nombre = "Super Administrador",
                            NombreUsuario = "superadmin",
                            PasswordHash = "$2a$11$SIyKkMyZWwKo6YzAZD6I2elyXLg4NB9DJGbFuBxEBAPtJ2tISXaUy",
                            Rol = 3
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Email = "admin@solicitudes.com",
                            FechaCreacion = new DateTime(2025, 12, 29, 11, 13, 9, 607, DateTimeKind.Local).AddTicks(7328),
                            Nombre = "Administrador",
                            NombreUsuario = "admin",
                            PasswordHash = "$2a$11$4eJWAmjWiyfbcImdowsK7uQVOopuGCEq9bqMPvzzZ5UW7XFAqNUy6",
                            Rol = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            AreaId = 1,
                            Email = "agente.ti@solicitudes.com",
                            FechaCreacion = new DateTime(2025, 12, 29, 11, 13, 9, 743, DateTimeKind.Local).AddTicks(7107),
                            Nombre = "Agente de TI",
                            NombreUsuario = "agenteti",
                            PasswordHash = "$2a$11$oKeA8yPnyfYQAoNMdoICfeOpOltmZV6p9bR6FskfHGTokQ6fSOiWO",
                            Rol = 4
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Email = "juan.perez@solicitudes.com",
                            FechaCreacion = new DateTime(2025, 12, 29, 11, 13, 9, 881, DateTimeKind.Local).AddTicks(5621),
                            Nombre = "Juan Pérez",
                            NombreUsuario = "usuario1",
                            PasswordHash = "$2a$11$/eShXgAC7PLhSEl.NtrNfecMOHUe4z6wmaEObKXLyvplhm23oQfqm",
                            Rol = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Comentario", b =>
                {
                    b.HasOne("Domain.Entities.Solicitud", "Solicitud")
                        .WithMany("Comentarios")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.HistorialEstado", b =>
                {
                    b.HasOne("Domain.Entities.Solicitud", "Solicitud")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Solicitud", b =>
                {
                    b.HasOne("Domain.Entities.Area", "Area")
                        .WithMany("Solicitudes")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "GestorAsignado")
                        .WithMany("SolicitudesAsignadas")
                        .HasForeignKey("GestorAsignadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Usuario", "Solicitante")
                        .WithMany("SolicitudesCreadas")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TipoSolicitud", "TipoSolicitud")
                        .WithMany("Solicitudes")
                        .HasForeignKey("TipoSolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("GestorAsignado");

                    b.Navigation("Solicitante");

                    b.Navigation("TipoSolicitud");
                });

            modelBuilder.Entity("Domain.Entities.TipoSolicitud", b =>
                {
                    b.HasOne("Domain.Entities.Area", "Area")
                        .WithMany("TiposSolicitud")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Domain.Entities.Area", "Area")
                        .WithMany("Usuarios")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Domain.Entities.Area", b =>
                {
                    b.Navigation("Solicitudes");

                    b.Navigation("TiposSolicitud");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Domain.Entities.Solicitud", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("HistorialEstados");
                });

            modelBuilder.Entity("Domain.Entities.TipoSolicitud", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("SolicitudesAsignadas");

                    b.Navigation("SolicitudesCreadas");
                });
#pragma warning restore 612, 618
        }
    }
}
